accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

cookie_stands/urls.py
from django.urls import path
from .views import CookieStandList, CookieStandDetail

urlpatterns = [
    path("", CookieStandList.as_view(), name="cookie_stand_list"),
    path("<int:pk>/", CookieStandDetail.as_view(), name="cookie_stand_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from .views import MyTokenObtainPairView
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/cookie_stands/", include("cookie_stands.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "api/token/",
        MyTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path("cookie_stands/", include("cookie_stands.urls_front")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username

cookie_stands/models.py
import random
from django.contrib.auth import get_user_model
from django.db import models


class CookieStand(models.Model):
    location = models.CharField(max_length=256)
    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    description = models.TextField(blank=True)
    hourly_sales = models.JSONField(default=list, null=True)
    minimum_customers_per_hour = models.IntegerField(default=0)
    maximum_customers_per_hour = models.IntegerField(default=0)
    average_cookies_per_sale = models.FloatField(default=0)

    def __str__(self):
        return self.location

    def save(self, *args, **kwargs):

        if not self.pk and not self.hourly_sales:
            min = self.minimum_customers_per_hour
            max = self.maximum_customers_per_hour

            cookies_each_hour = [
                int(random.randint(min, max) * self.average_cookies_per_sale)
                for _ in range(14)
            ]

            self.hourly_sales = cookies_each_hour

        super().save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

cookie_stands/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from .models import CookieStand
from .permissions import IsOwnerOrReadOnly
from .serializers import CookieStandSerializer


class CookieStandList(ListCreateAPIView):
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer


class CookieStandDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer

project/views.py
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView


class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token["email"] = user.email
        token["username"] = user.username
        # ...

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="w-3/4 mx-auto max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="flex justify-end px-4 pt-4">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2" aria-labelledby="dropdownButton">
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Edit</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Export Data</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete</a>
            </li>
            </ul>
        </div>
    </div>
    <div class="flex flex-col items-center pb-10 px-4">
        <img class="w-96 h-96 mb-3 rounded-full shadow-lg" src="https://ca.slack-edge.com/T039KG69K-U03V0N804HE-a1af50c10b55-512" alt="Eric image"/>
        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Eric Mungai Kinuthia</h5>
        <span class="text-sm text-gray-500 dark:text-gray-400">Full Stack Developer</span>
        <div class="flex mt-4 space-x-3 md:mt-6">
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add friend</a>
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700">Message</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}All the Cookie Stands{% endblock %}</title>
 <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-green-50">
<header>
  <nav class="bg-gray-900 border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
        <div class="container flex flex-wrap items-center justify-between mx-auto">
          <a href="{% url 'home' %}">
              <img src="https://upload.wikimedia.org/wikipedia/commons/7/78/Things_Logo.svg" class="p-3 h-12 bg-white rounded" alt="Logo" />
          </a>
          <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
            <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}" class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent  md:p-0 dark:text-white" aria-current="page">Log Out</a>
              </li>
              {% else %}
              <li>
                <a href="{% url 'login' %}" class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent  md:p-0 dark:text-white" aria-current="page">Log In</a>
              </li>
            {% endif %}

              <li>
                <a href="{% url 'about' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
              </li>
              {% if request.user.is_authenticated %}
                <li>
                <a href="{% url 'cookie_stand_list' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">List</a>
                </li>
                 <li>
                <a href="{% url 'cookie_stand_create' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Create</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
</header>
<main>
<div class="container mx-auto mt-4">
  {% block content %}
  {% endblock content %}
</div>
</main>
<footer
      class="bg-gray-900
             text-sm text-white
             fixed
             inset-x-0
             bottom-0
             p-2">
      &copy; CodeFellows 2023
    </footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
</body>
</html>

templates/cookie_stands/cookie_stand_create.html
{% extends 'base.html' %}

{% block content %}


  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">

    <form class="mb-6 text-black space-y-6 flex flex-col justify-center items-center " action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded">Create</button>
    </form>
  </div>

{% endblock content %}

templates/cookie_stands/cookie_stand_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cookie Stand</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ object.location }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/cookie_stands/cookie_stand_detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <a href="#"
       class="block max-w-sm p-6 bg-white border text-white border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
      <h2>Location: {{ object.location }}</h2>
      <p>Owner: {{ object.owner }}</p>
      <p>Description: {{ object.description }}</p>
      <p>Hourly Sales: {{ object.hourly_sales }}</p>
      <p>Min Customers/Hour: {{ object.minimum_customers_per_hour }}</p>
      <p>Max Customers/Hour: {{ object.maximum_customer_per_hour }}</p>
      <p>Average Cookies/Sale: {{ object.average_cookies_per_sale }}</p>
    </a>
  </div>

  <br>
  <div>
    <p class="m-2"><a href="{% url 'cookie_stand_update' object.pk %}"
                      class="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded">Update</a></p>
    <p class="m-2"><a href="{% url 'cookie_stand_delete' object.pk %}"
                      class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</a></p>
  </div>


{% endblock content %}

templates/cookie_stands/cookie_stand_list.html
{% extends 'base.html' %}

{% block content %}

  <div class="space-y-8 p-8">

  <h1 class="text-4xl text-center">Cookie Stands</h1>
  <div
    class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
    {% for cookie_stand in object_list %}
      <a href="{% url 'cookie_stand_detail' cookie_stand.pk %}" aria-current="true"
         class="block w-full px-4 py-4 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
        {{ cookie_stand.location }}
      </a>
    {% endfor %}
  </div>

  </div>

{% endblock content %}

templates/cookie_stands/cookie_stand_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Thing</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Cookie Stand</h5>
      <form class="mb-6 text-black space-y-6 flex flex-col justify-center items-center " action="" method="POST" action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <input class="bg-indigo-500 hover:bg-indigo-600 text-black font-bold py-2 px-4 rounded" type="submit" value="save">
        </form>

    </form>
  </div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <div class="space-y-8">

  <h2 class="text-4xl">Hi {{ user.username }}!</h2>
  <p>Maybe one day you'll see a glorious home page here.</p>
  <p>But for now just  notice that List and Create are in Nav bar.</p>
  </div>

{% else %}
  <div class="flex flex-col space-y-8">

  <h2 class="text-4xl">Hi there. You're not logged in :(</h2>
  <p>To get all the "things" you need to log in, or set up an account.</p>
  <a class="w-1/4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" href="{% url 'login' %}">Log In</a>
  <a class="w-1/4 focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" href="{% url 'signup' %}">Sign Up</a>
  </div>
{% endif %}
{% endblock %}

templates/things/thing_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Thing</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ thing.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/things/thing_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Thing</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Thing</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ thing.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ thing.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == thing.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ thing.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}